runtime: python39
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
    secure: always
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_instances: 0
  max_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 10ms

service_account: appengine@presidio-405700.iam.gserviceaccount.com